version: 2
jobs:
  test-node8:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
  test-node9:
    docker:
      - image: node:9-alpine
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
workflows:
  version: 2
  build:
    jobs:
      - test-node8
      - test-node9
