version: 2
jobs:
  test-node8:
    docker:
      - image: node:8-alpine
    steps:
      - run: apk add --no-cache make bash git yarn
      - checkout
      - restore_cache:
          keys:
          - node8-dependencies-{{ checksum "yarn.lock" }}
          - node8-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node8-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
  test-node9:
    docker:
      - image: node:9-alpine
    steps:
      - run: apk add --no-cache make bash git yarn
      - checkout
      - restore_cache:
          keys:
          - node8-dependencies-{{ checksum "yarn.lock" }}
          - node8-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node8-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
workflows:
  version: 2
  build:
    jobs:
      - test-node8
      - test-node9
